# --- ÉTAPE 1 : Le Build ---
FROM node:20-alpine AS builder
WORKDIR /app

# On copie les fichiers de dépendances
COPY package*.json ./
RUN npm install

# On copie tout le code source (pense au .dockerignore !)
COPY . .

# On lance la commande de build de Vite
RUN npm run build

# --- ÉTAPE 2 : Le Serveur (Nginx) ---
FROM nginx:alpine

# Vite met tout dans le dossier 'dist'
COPY --from=builder /app/dist /usr/share/nginx/html

# Si tu as un fichier de config Nginx perso (sinon commente cette ligne)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]